# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unofficial Education Center of MOEL
email: labor.barkle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I created this GitHub to introduce IT technology and computer programming to my colleagues at the Department of Employment and Labor.
  이 깃허브는 고용노동부 동료들에게 IT기술과 컴퓨터 프로그래밍에 대해 소개하려고 만들었습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://barkle2.github.io" # the base hostname & protocol for your site
github_username:  barkle2

# Build settings
markdown: kramdown
